spring:
  profiles:
    active:
      - ${APP_PROFILE:test}
  jpa:
    open-in-view: false
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

server:
  servlet:
    context-path: '/api'