server:
  port: 9090

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: ${HIBERNATE_SHOW_SQL:true}
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

logging:
  level:
    br.com.gabrielferreira.users: TRACE

users.api.base-uri: http://localhost:9090/api/users/